enyo.depends(
	"views.js",
	"divider.js",
	"baseview.js",
	"mainview.js",
	"folderview.js",
	"feedview.js",
	"articleview.js",
	"oauthiframe.js",
	"logindialog.js",
	"notificationfeedsdialog.js",
	"preferencesview.js",
	"helpview.js",
	"addview.js"
);
